In [1]:
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
from elfen.util import normalize_column

import mantel
from itertools import combinations
import numpy as np
from sentence_transformers.util import cos_sim
from tqdm import tqdm

from src.utils import get_inf_feats, get_null_feats, get_nan_feats, symmetric_to_condensed

In [2]:
def get_conditions():
    conditions = [
        # INDIVIDUAL CONDITIONS
        # Human arguments
        (pl.col("model") == "Human"),
        # model, default (no context, no sociodemographic info, 
        # no explanation (info), no pros+cons)
        ((pl.col("context") == False),
         (pl.col("sociodemographic_info").is_null()),
         (pl.col("info").is_null()),
         (pl.col("pro").is_null()),
         (pl.col("contra").is_null())),
        # model, context only
        ((pl.col("model") != "Human"),
         (pl.col("context") == True),
         (pl.col("sociodemographic_info").is_null()),
         (pl.col("info").is_null()),
         (pl.col("pro").is_null()),
         (pl.col("contra").is_null())),
        # model, sociodemographic info only
        ((pl.col("model") != "Human"),
         (pl.col("context") == False),
         (pl.col("sociodemographic_info").is_not_null()),
         (pl.col("info").is_null()),
         (pl.col("pro").is_null()),
         (pl.col("contra").is_null())),
        # model, explanation (info) only
        ((pl.col("model") != "Human"),
         (pl.col("context") == False),
         (pl.col("sociodemographic_info").is_null()),
         (pl.col("info").is_not_null()),
         (pl.col("pro").is_null()),
         (pl.col("contra").is_null())),
        # model, pros+cons only
        ((pl.col("model") != "Human"),
         (pl.col("context") == False),
         (pl.col("sociodemographic_info").is_null()),
         (pl.col("info").is_null()),
         (pl.col("pro").is_not_null()),
         (pl.col("contra").is_not_null())),
        # TWO-WAY INTERACTIONS
        # model, context + sociodemographic info
        ((pl.col("model") != "Human"),
         (pl.col("context") == True),
         (pl.col("sociodemographic_info").is_not_null()),
         (pl.col("info").is_null()),
         (pl.col("pro").is_null()),
         (pl.col("contra").is_null())),
        # model, context + explanation (info)
        ((pl.col("model") != "Human"),
         (pl.col("context") == True),
         (pl.col("sociodemographic_info").is_null()),
         (pl.col("info").is_not_null()),
         (pl.col("pro").is_null()),
         (pl.col("contra").is_null())),
        # model, context + pros+cons
        ((pl.col("model") != "Human"),
         (pl.col("context") == True),
         (pl.col("sociodemographic_info").is_null()),
         (pl.col("info").is_null()),
         (pl.col("pro").is_not_null()),
         (pl.col("contra").is_not_null())),
        # model, sociodemographic info + explanation (info)
        ((pl.col("model") != "Human"),
         (pl.col("context") == False),
         (pl.col("sociodemographic_info").is_not_null()),
         (pl.col("info").is_not_null()),
         (pl.col("pro").is_null()),
         (pl.col("contra").is_null())),
        # model, sociodemographic info + pros+cons
        ((pl.col("model") != "Human"),
         (pl.col("context") == False),
         (pl.col("sociodemographic_info").is_not_null()),
         (pl.col("info").is_null()),
         (pl.col("pro").is_not_null()),
         (pl.col("contra").is_not_null())),
        # model, explanation (info) + pros+cons
        ((pl.col("model") != "Human"),
         (pl.col("context") == False),
         (pl.col("sociodemographic_info").is_null()),
         (pl.col("info").is_not_null()),
         (pl.col("pro").is_not_null()),
         (pl.col("contra").is_not_null())),
        # THREE-WAY INTERACTIONS
        # model, context + sociodemographic info + explanation (info)
        ((pl.col("model") != "Human"),
         (pl.col("context") == True),
         (pl.col("sociodemographic_info").is_not_null()),
         (pl.col("info").is_not_null()),
         (pl.col("pro").is_null()),
         (pl.col("contra").is_null())),
        # model, context + sociodemographic info + pros+cons
        ((pl.col("model") != "Human"),
         (pl.col("context") == True),
         (pl.col("sociodemographic_info").is_not_null()),
         (pl.col("info").is_null()),
         (pl.col("pro").is_not_null()),
         (pl.col("contra").is_not_null())),
        # model, context + explanation (info) + pros+cons
        ((pl.col("model") != "Human"),
         (pl.col("context") == True),
         (pl.col("sociodemographic_info").is_null()),
         (pl.col("info").is_not_null()),
         (pl.col("pro").is_not_null()),
         (pl.col("contra").is_not_null())),
        # model, sociodemographic info + explanation (info) + pros+cons
        ((pl.col("model") != "Human"),
         (pl.col("context") == False),
         (pl.col("sociodemographic_info").is_not_null()),
         (pl.col("info").is_not_null()),
         (pl.col("pro").is_not_null()),
         (pl.col("contra").is_not_null())),
        # ALL CONDITIONS
        # model, context + sociodemographic info + explanation (info) + pros+cons
        ((pl.col("model") != "Human"),
         (pl.col("context") == True),
         (pl.col("sociodemographic_info").is_not_null()),
         (pl.col("info").is_not_null()),
         (pl.col("pro").is_not_null()),
         (pl.col("contra").is_not_null()))
    ]
    condition_names = [
        "Human",
        "Default",
        "C",
        "SD",
        "Ex",
        "P&C",
        "C + SD",
        "C + Ex",
        "C + P&C",
        "SD + Ex",
        "SD + P&C",
        "Ex + P&C",
        "C + SD + Ex",
        "C + SD + P&C",
        "C + Ex + P&C",
        "SD + Ex + P&C",
        "C + SD + Ex + P&C"
    ]
    return conditions, condition_names

In [3]:
def add_conditions(df):
    conditions = df.with_columns(pl.lit("Dummy").alias("condition"))

    for condition, condition_name in zip(*get_conditions()):
        conditions = conditions.with_columns(
            pl.when(condition).then(pl.lit(condition_name))
            .otherwise(pl.col("condition")).alias("condition"))

    return conditions

# Load the data

In [4]:
prompts_de = pl.read_csv("prompts_de.csv")
prompts_fr = pl.read_csv("prompts_fr.csv")
prompts_it = pl.read_csv("prompts_it.csv")

In [5]:
prompts_de.head()

shape: (5, 10)
┌──────┬─────────────────┬───────────────────────┬────────┬───┬──────┬──────┬────────┬─────────┐
│ id   ┆ prompt          ┆ question              ┆ stance ┆ … ┆ info ┆ pro  ┆ contra ┆ context │
│ ---  ┆ ---             ┆ ---                   ┆ ---    ┆   ┆ ---  ┆ ---  ┆ ---    ┆ ---     │
│ str  ┆ str             ┆ str                   ┆ str    ┆   ┆ str  ┆ str  ┆ str    ┆ bool    │
╞══════╪═════════════════╪═══════════════════════╪════════╪═══╪══════╪══════╪════════╪═════════╡
│ de_0 ┆ Sie gehören der ┆ Bei Ehepaaren ist die ┆ FAVOR  ┆ … ┆ null ┆ null ┆ null   ┆ false   │
│      ┆ folgenden sozi… ┆ Höhe der…             ┆        ┆   ┆      ┆      ┆        ┆         │
│ de_1 ┆ Sie gehören der ┆ Bei Ehepaaren ist die ┆ FAVOR  ┆ … ┆ null ┆ null ┆ null   ┆ false   │
│      ┆ folgenden sozi… ┆ Höhe der…             ┆        ┆   ┆      ┆      ┆        ┆         │
│ de_2 ┆ Sie gehören der ┆ Bei Ehepaaren ist die ┆ FAVOR  ┆ … ┆ null ┆ null ┆ null   ┆ false   │
│      ┆ folgenden sozi… ┆ Höhe der…             ┆        ┆   ┆      ┆      ┆        ┆         │
│ de_3 ┆ Sie gehören der ┆ Bei Ehepaaren ist die ┆ FAVOR  ┆ … ┆ null ┆ null ┆ null   ┆ false   │
│      ┆ folgenden sozi… ┆ Höhe der…             ┆        ┆   ┆      ┆      ┆        ┆         │
│ de_4 ┆ Sie gehören der ┆ Bei Ehepaaren ist die ┆ FAVOR  ┆ … ┆ null ┆ null ┆ null   ┆ false   │
│      ┆ folgenden sozi… ┆ Höhe der…             ┆        ┆   ┆      ┆      ┆        ┆         │
└──────┴─────────────────┴───────────────────────┴────────┴───┴──────┴──────┴────────┴─────────┘

In [6]:
corpus_de = pl.read_csv("output/processed/corpus_de_features.csv")
corpus_fr = pl.read_csv("output/processed/corpus_fr_features.csv")
corpus_it = pl.read_csv("output/processed/corpus_it_features.csv")

In [7]:
# get the question_id from the corpus and prompts dataframes to parallelize the dataframes later
question2prompts_de = prompts_de.join(corpus_de.select(["ID_question", "question"]), on="question", how="inner").select(["ID_question", "id"])
question2prompts_fr = prompts_fr.join(corpus_fr.select(["ID_question", "question"]), on="question", how="inner").select(["ID_question", "id"])
question2prompts_it = prompts_it.join(corpus_it.select(["ID_question", "question"]), on="question", how="inner").select(["ID_question", "id"])
# delete duplicate rows in question2prompts dataframes
question2prompts_de = question2prompts_de.unique()
question2prompts_fr = question2prompts_fr.unique()
question2prompts_it = question2prompts_it.unique()
# combine the question2prompts dataframes into one dataframe
question2prompts = pl.concat([question2prompts_de, question2prompts_fr, question2prompts_it], how="vertical")

In [8]:
# Load the data for LLaMA 4 Scout
df_de_llama4 = pl.read_csv("output/processed/llama4scout_de_features.csv"). \
    join(prompts_de, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("llama_4_scout").alias("model"),
                 pl.lit("de").alias("language"))
df_fr_llama4 = pl.read_csv("output/processed/llama4scout_fr_features.csv"). \
    join(prompts_fr, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("llama_4_scout").alias("model"),
                 pl.lit("fr").alias("language"))
df_it_llama4 = pl.read_csv("output/processed/llama4scout_it_features.csv"). \
    join(prompts_it, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("llama_4_scout").alias("model"),
                 pl.lit("it").alias("language"))

# Load the data for GPT 4.1 Mini
df_de_gpt = pl.read_csv("output/processed/gpt-4.1-mini_de_features.csv"). \
    join(prompts_de, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("gpt-4.1-mini").alias("model"),
                 pl.lit("de").alias("language"))
df_fr_gpt = pl.read_csv("output/processed/gpt-4.1-mini_fr_features.csv"). \
    join(prompts_fr, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("gpt-4.1-mini").alias("model"),
                 pl.lit("fr").alias("language"))
df_it_gpt = pl.read_csv("output/processed/gpt-4.1-mini_it_features.csv"). \
    join(prompts_it, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("gpt-4.1-mini").alias("model"),
                 pl.lit("it").alias("language"))

# Load the data for LLaMA 3.1-8B-Instruct
df_de_llama3 = pl.read_csv("output/processed/llama3.1-8b-instruct_de_features.csv"). \
    join(prompts_de, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("llama_3.1-8b-instruct").alias("model"),
                 pl.lit("de").alias("language"))
df_fr_llama3 = pl.read_csv("output/processed/llama3.1-8b-instruct_fr_features.csv"). \
    join(prompts_fr, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("llama_3.1-8b-instruct").alias("model"),
                 pl.lit("fr").alias("language"))
df_it_llama3 = pl.read_csv("output/processed/llama3.1-8b-instruct_it_features.csv"). \
    join(prompts_it, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("llama_3.1-8b-instruct").alias("model"),
                 pl.lit("it").alias("language"))

# Load the data for Occiglot-7B-EU5 Instruct
df_de_occiglot = pl.read_csv("output/processed/occiglot-7b-eu5-instruct_de_features.csv"). \
    join(prompts_de, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("occiglot-7b-eu5-instruct").alias("model"),
                 pl.lit("de").alias("language"))
df_fr_occiglot = pl.read_csv("output/processed/occiglot-7b-eu5-instruct_fr_features.csv"). \
    join(prompts_fr, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("occiglot-7b-eu5-instruct").alias("model"),
                 pl.lit("fr").alias("language"))
df_it_occiglot = pl.read_csv("output/processed/occiglot-7b-eu5-instruct_it_features.csv"). \
    join(prompts_it, left_on="prompt_id", right_on="id", how="left"). \
    with_columns(pl.lit("occiglot-7b-eu5-instruct").alias("model"),
                 pl.lit("it").alias("language"))

In [9]:
# Get shared columns
shared_columns = set(df_de_llama4.columns) & set(df_fr_llama4.columns) & set(df_it_llama4.columns) & set(df_de_gpt.columns) & set(df_fr_gpt.columns) & set(df_it_gpt.columns) & set(df_de_llama3.columns) & set(df_fr_llama3.columns) & set(df_it_llama3.columns) & set(df_de_occiglot.columns) & set(df_fr_occiglot.columns) & set(df_it_occiglot.columns)

In [10]:
ordered_shared_columns = [col for col in df_de_llama4.columns if col in shared_columns]

In [11]:
# Combine all dataframes
df_generated = pl.concat([df_de_llama4.select(ordered_shared_columns),
                         df_fr_llama4.select(ordered_shared_columns),
                         df_it_llama4.select(ordered_shared_columns),
                         df_de_gpt.select(ordered_shared_columns),
                         df_fr_gpt.select(ordered_shared_columns),
                         df_it_gpt.select(ordered_shared_columns),
                         df_de_llama3.select(ordered_shared_columns),
                         df_fr_llama3.select(ordered_shared_columns),
                         df_it_llama3.select(ordered_shared_columns),
                         df_de_occiglot.select(ordered_shared_columns),
                         df_fr_occiglot.select(ordered_shared_columns),
                         df_it_occiglot.select(ordered_shared_columns)])

In [12]:
df_generated["sociodemographic_info"].n_unique()

8

In [13]:
for row in df_generated["sociodemographic_group"].value_counts().rows():
    print(row)

('Stadt', 4608)
('Andere Kirchen/Religionsgemeinschaften', 2280)
('Rechts und Liberal', 7056)
('18-34', 12792)
('Anderer Bildungsabschluss', 8184)
('35-49', 12072)
('Universität', 13848)
('Andere christliche Gemeinschaften', 8040)
('Verwitwet', 6960)
('Männlich', 13872)
('Römisch-katholisch', 13536)
('Konfessionslos', 12480)
('Links und Konservativ', 8760)
('Land', 13896)
(None, 13896)
('Mitte und Liberal', 7440)
('Jüdische Gemeinschaften', 744)
('In Partnerschaft', 8736)
('Berufsmatura', 6936)
('Islamische Gemeinschaften', 4584)
('Höhere Fachschule', 4992)
('Rechts und Konservativ', 3840)
('Mitte und Konservativ', 11184)
('Christ-katholisch', 8664)
('Höhere Berufsausbildung', 8688)
('Mitte und Konservativ-Liberal', 11208)
('Geschieden', 8304)
('Verheiratet', 13176)
('Fachhochschule', 9264)
('Ledig', 13323)
('Berufslehre oder Berufsschule', 8784)
('Links und Konservativ-Liberal', 12504)
('Sekundarschule', 4776)
('Anderes Geschlecht', 2232)
('Keine Schulbildung', 432)
('Weiblich', 10848)
('In eingetragene Partnerschaft', 1512)
('65+', 9504)
('Handelsschule oder Handelsdiplom', 2688)
('Rechts und Konservativ-Liberal', 6624)
('50-64', 13176)
('Links und Liberal', 4800)
('Getrennt', 7272)
('Anlehre', 504)
('Evangelisch-reformiert', 9216)
('Gymnasium oder Seminar', 7824)
('Christlich-orthodox', 4152)
('Primarschule oder Realschule', 2472)
('Diplommittelschule', 3288)

In [14]:
# recode sociodemographic features in the generated dataframe to match the corpus dataframe
df_generated = df_generated.with_columns(
    pl.when(pl.col("sociodemographic_info") == "gender")
    .then(pl.col("sociodemographic_group"))
    .otherwise(None).alias("gender"),
    pl.when(pl.col("sociodemographic_info") == "age")
    .then(pl.col("sociodemographic_group"))
    .otherwise(None).alias("age"),
    pl.when(pl.col("sociodemographic_info") == "education")
    .then(pl.col("sociodemographic_group"))
    .otherwise(None).alias("education"),
    pl.when(pl.col("sociodemographic_info") == "civil_status")
    .then(pl.col("sociodemographic_group"))
    .otherwise(None).alias("civil_status"),
    pl.when(pl.col("sociodemographic_info") == "denomination")
    .then(pl.col("sociodemographic_group"))
    .otherwise(None).alias("denomination"),
    pl.when(pl.col("sociodemographic_info") == "residence")
    .then(pl.col("sociodemographic_group"))
    .otherwise(None).alias("residence"),
    pl.when(pl.col("sociodemographic_info") == "political_spectrum")
    .then(pl.col("sociodemographic_group"))
    .otherwise(None).alias("political_spectrum")
)

In [15]:
# Join the generated dataframe with the question2prompts dataframe to get the question_id for each generated argument
df_generated = df_generated.join(question2prompts, left_on="prompt_id", right_on="id", how="left")

In [16]:
df_generated.head()

shape: (5, 201)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ output    ┆ output_id ┆ prompt_id ┆ raw_seque ┆ … ┆ denominat ┆ residence ┆ political ┆ ID_quest │
│ ---       ┆ ---       ┆ ---       ┆ nce_lengt ┆   ┆ ion       ┆ ---       ┆ _spectrum ┆ ion      │
│ str       ┆ str       ┆ str       ┆ h         ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆ str       ┆           ┆ str       ┆ i64      │
│           ┆           ┆           ┆ i64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Die Begre ┆ 2025-07-1 ┆ de_0      ┆ 302       ┆ … ┆ null      ┆ null      ┆ null      ┆ 32216    │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Rente auf ┆ 0.4959171 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1…        ┆ 36Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Die Begre ┆ 2025-07-1 ┆ de_0      ┆ 357       ┆ … ┆ null      ┆ null      ┆ null      ┆ 32216    │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Rente für ┆ 1.8350587 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ E…        ┆ 34Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Die Begre ┆ 2025-07-1 ┆ de_0      ┆ 490       ┆ … ┆ null      ┆ null      ┆ null      ┆ 32216    │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Rente auf ┆ 3.5557549 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1…        ┆ 15Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Die Begre ┆ 2025-07-1 ┆ de_1      ┆ 324       ┆ … ┆ null      ┆ null      ┆ null      ┆ 32216    │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Rentenhöh ┆ 4.9513965 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ e …       ┆ 43Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Ich       ┆ 2025-07-1 ┆ de_1      ┆ 320       ┆ … ┆ null      ┆ null      ┆ null      ┆ 32216    │
│ denke,    ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ die Begre ┆ 6.1802421 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ nzung der ┆ 53Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [17]:
corpus_de["topic"].n_unique()

13

In [18]:
# Add model column to corpus dataframes
corpus_de = corpus_de.with_columns(pl.lit("Human").alias("model"))
corpus_fr = corpus_fr.with_columns(pl.lit("Human").alias("model"))
corpus_it = corpus_it.with_columns(pl.lit("Human").alias("model"))

# get shared columns between corpus dataframes
shared_columns_corpus = set(corpus_de.columns) & set(corpus_fr.columns) & set(corpus_it.columns)
ordered_shared_columns = [col for col in corpus_de.columns if col in shared_columns_corpus]

# Combine all dataframes
df_corpus = pl.concat([corpus_de.select(ordered_shared_columns),
                      corpus_fr.select(ordered_shared_columns),
                      corpus_it.select(ordered_shared_columns)])

# delete subcorpus dataframes to save memory
del df_de_llama4, df_fr_llama4, df_it_llama4, df_de_gpt, df_fr_gpt, df_it_gpt, df_de_llama3, df_fr_llama3, df_it_llama3, df_de_occiglot, df_fr_occiglot, df_it_occiglot, corpus_de, corpus_fr, corpus_it

In [19]:
df_corpus["topic"].n_unique()

13

In [20]:
# get the difference between the generated and corpus dataframes columns
diff_columns_corpus = set(df_generated.columns) - set(df_corpus.columns)
diff_columns_generated = set(df_corpus.columns) - set(df_generated.columns)
print(diff_columns_corpus, diff_columns_generated)

{'output_id', 'sociodemographic_info', 'prompt_id', 'n_PRON_Person_2', 'sociodemographic_group', 'output', 'prompt', 'context'} {'topic', 'argument_id', 'argument', 'n_intj'}

In [21]:
# Remove n_PRON_Person_2 from diff_columns_corpus as it is not a relevant feature for our analysis
diff_columns_corpus.remove("n_PRON_Person_2")
df_generated = df_generated.drop("n_PRON_Person_2")
# Remove n_intj from diff_columns_generated as it is not a relevant feature for our analysis
diff_columns_generated.remove("n_intj")
df_corpus = df_corpus.drop("n_intj")

In [22]:
# rename output_id to argument_id in the generated dataframe
df_generated = df_generated.rename({"output_id": "argument_id"})
# rename output to argument in the generated dataframe
df_generated = df_generated.rename({"output": "argument"})

In [23]:
# Remove unnecessary columns from the generated dataframe
df_generated = df_generated.drop([
    "prompt"
])
# add "context" column to the corpus dataframe with True as a dummy
df_corpus = df_corpus.with_columns(pl.lit(True).alias("context"))
# add sociodemographic_info column to the corpus dataframe with None as a dummy
df_corpus = df_corpus.with_columns(pl.lit(None).alias("sociodemographic_info"),
                                   pl.lit(None).alias("sociodemographic_group"))

In [24]:
# create ID_question2topic dictionary
id_question2topic = df_corpus.select(["ID_question", "topic"]).unique()
id_question2topic = {row[0]: row[1] for row in id_question2topic.iter_rows()}

# map the topic column in the generated dataframe using the ID_question2topic dictionary
df_generated = df_generated.with_columns(pl.col("ID_question").replace_strict(id_question2topic).alias("topic"))

In [25]:
# add dummy prompt_id column to the corpus dataframe
df_corpus = df_corpus.with_columns(pl.lit(None).alias("prompt_id"))

In [26]:
# shared columns between the generated and corpus dataframes
shared_columns = set(df_generated.columns) & set(df_corpus.columns)
ordered_shared_columns = [col for col in df_generated.columns if col in shared_columns]

In [27]:
len(ordered_shared_columns)

200

In [28]:
# get types per column for the generated and corpus dataframes
generated_types = df_generated.select(ordered_shared_columns).dtypes
corpus_types = df_corpus.select(ordered_shared_columns).dtypes
# print the name of the column where the type is different between the generated and corpus dataframes
for i, (gen_type, corp_type) in enumerate(zip(generated_types, corpus_types)):
    if gen_type != corp_type:
        print(f"Column {ordered_shared_columns[i]} has different types: generated={gen_type}, corpus={corp_type}")

Column argument_id has different types: generated=String, corpus=Int64
Column prompt_id has different types: generated=String, corpus=Null
Column sociodemographic_info has different types: generated=String, corpus=Null
Column sociodemographic_group has different types: generated=String, corpus=Null

In [29]:
df_generated = df_generated.with_columns(pl.col("argument_id").cast(pl.String))
df_corpus = df_corpus.with_columns(pl.col("argument_id").cast(pl.String))
df_corpus = df_corpus.with_columns(pl.col("sociodemographic_info").cast(pl.String),
                                   pl.col("sociodemographic_group").cast(pl.String))
df_corpus = df_corpus.with_columns(pl.col("prompt_id").cast(pl.String))

In [30]:
# Combine all dataframes
df = pl.concat([df_generated.select(ordered_shared_columns), df_corpus.select(ordered_shared_columns)], how="vertical")

In [31]:
df.describe()

shape: (9, 201)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ argument ┆ argument_ ┆ prompt_id ┆ … ┆ residence ┆ political ┆ ID_questi ┆ topic     │
│ ---       ┆ ---      ┆ id        ┆ ---       ┆   ┆ ---       ┆ _spectrum ┆ on        ┆ ---       │
│ str       ┆ str      ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str       │
│           ┆          ┆ str       ┆           ┆   ┆           ┆ str       ┆ f64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 398729   ┆ 398729    ┆ 385971    ┆ … ┆ 31262     ┆ 86156     ┆ 398729.0  ┆ 398729    │
│ null_coun ┆ 0        ┆ 0         ┆ 12758     ┆ … ┆ 367467    ┆ 312573    ┆ 0.0       ┆ 0         │
│ t         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 32249.312 ┆ null      │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 646       ┆           │
│ std       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 20.148834 ┆ null      │
│ min       ┆          ┆ 202300    ┆ de_0      ┆ … ┆ Land      ┆ Links und ┆ 32216.0   ┆ Democracy │
│           ┆          ┆           ┆           ┆   ┆           ┆ Konservat ┆           ┆ , Media & │
│           ┆          ┆           ┆           ┆   ┆           ┆ iv        ┆           ┆ Digitizat │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ io…       │
│ 25%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 32229.0   ┆ null      │
│ 50%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 32249.0   ┆ null      │
│ 75%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 32264.0   ┆ null      │
│ max       ┆ �        ┆ chatcmpl- ┆ it_999    ┆ … ┆ Stadt     ┆ Rechts    ┆ 32288.0   ┆ Welfare   │
│           ┆          ┆ CR9IPAjqa ┆           ┆   ┆           ┆ und       ┆           ┆ state &   │
│           ┆          ┆ zUdb4r1tv ┆           ┆   ┆           ┆ Liberal   ┆           ┆ family    │
│           ┆          ┆ sz8…      ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [32]:
df.filter(pl.col("model") == "Human").shape

(12758, 200)

In [33]:
df.columns

['argument',
 'argument_id',
 'prompt_id',
 'raw_sequence_length',
 'n_tokens',
 'n_sentences',
 'tokens_per_sentence',
 'n_characters',
 'avg_word_length',
 'n_types',
 'n_long_words',
 'n_lemmas',
 'n_VERB_VerbForm_Fin',
 'n_VERB_VerbForm_Inf',
 'n_VERB_VerbForm_Part',
 'n_VERB_Mood_Imp',
 'n_VERB_Mood_Ind',
 'n_VERB_Mood_Sub',
 'n_VERB_Tense_Past',
 'n_VERB_Tense_Pres',
 'n_VERB_Person_1',
 'n_VERB_Person_2',
 'n_VERB_Person_3',
 'n_VERB_Number_Plur',
 'n_VERB_Number_Sing',
 'n_NOUN_Gender_Fem',
 'n_NOUN_Gender_Masc',
 'n_NOUN_Number_Plur',
 'n_NOUN_Number_Sing',
 'n_PRON_PronType_Dem',
 'n_PRON_PronType_Int',
 'n_PRON_PronType_Prs',
 'n_PRON_PronType_Rel',
 'n_PRON_Gender_Fem',
 'n_PRON_Gender_Masc',
 'n_PRON_Number_Plur',
 'n_PRON_Number_Sing',
 'n_PRON_Person_1',
 'n_PRON_Person_3',
 'n_ADJ_Gender_Fem',
 'n_ADJ_Gender_Masc',
 'n_ADJ_Number_Plur',
 'n_ADJ_Number_Sing',
 'n_DET_Gender_Fem',
 'n_DET_Gender_Masc',
 'n_DET_Number_Plur',
 'n_DET_Number_Sing',
 'n_DET_Definite_Def',
 'n_DET_Definite_Ind',
 'tree_width',
 'tree_depth',
 'tree_branching',
 'n_noun_chunks',
 'n_dependency_cc',
 'n_dependency_dep',
 'n_dependency_punct',
 'n_positive_sentiment',
 'n_negative_sentiment',
 'sentiment_score',
 'avg_valence',
 'n_low_valence',
 'n_high_valence',
 'avg_arousal',
 'n_low_arousal',
 'n_high_arousal',
 'avg_dominance',
 'n_low_dominance',
 'n_high_dominance',
 'avg_intensity_anger',
 'avg_intensity_anticipation',
 'avg_intensity_disgust',
 'avg_intensity_fear',
 'avg_intensity_joy',
 'avg_intensity_sadness',
 'avg_intensity_surprise',
 'avg_intensity_trust',
 'n_low_intensity_anger',
 'n_low_intensity_anticipation',
 'n_low_intensity_disgust',
 'n_low_intensity_fear',
 'n_low_intensity_joy',
 'n_low_intensity_sadness',
 'n_low_intensity_surprise',
 'n_low_intensity_trust',
 'n_high_intensity_anger',
 'n_high_intensity_anticipation',
 'n_high_intensity_disgust',
 'n_high_intensity_fear',
 'n_high_intensity_joy',
 'n_high_intensity_sadness',
 'n_high_intensity_surprise',
 'n_high_intensity_trust',
 'compressibility',
 'entropy',
 'lemma_token_ratio',
 'ttr',
 'rttr',
 'cttr',
 'herdan_c',
 'summer_index',
 'dugast_u',
 'maas_index',
 'n_lexical_tokens',
 'lexical_density',
 'n_hapax_legomena',
 'n_global_token_hapax_legomena',
 'n_global_lemma_hapax_legomena',
 'n_hapax_dislegomena',
 'n_global_token_hapax_dislegomena',
 'n_global_lemma_hapax_dislegomena',
 'sichel_s',
 'global_sichel_s',
 'giroud_index',
 'mtld',
 'hdd',
 'mattr',
 'msttr',
 'yule_k',
 'simpsons_d',
 'herdan_v',
 'pos_variability',
 'n_adj',
 'n_adp',
 'n_adv',
 'n_aux',
 'n_cconj',
 'n_det',
 'n_noun',
 'n_num',
 'n_pron',
 'n_propn',
 'n_punct',
 'n_sconj',
 'n_verb',
 'n_x',
 'avg_concreteness',
 'n_high_concreteness',
 'avg_sd_concreteness',
 'n_syllables',
 'n_monosyllables',
 'n_polysyllables',
 'flesch_reading_ease',
 'flesch_kincaid_grade',
 'gunning_fog',
 'ari',
 'smog',
 'cli',
 'lix',
 'rix',
 'avg_n_synsets',
 'avg_n_synsets_noun',
 'avg_n_synsets_verb',
 'avg_n_synsets_adj',
 'n_low_synsets',
 'n_high_synsets',
 'n_high_synsets_noun',
 'n_high_synsets_verb',
 'n_high_synsets_adj',
 'n_low_synsets_noun',
 'n_low_synsets_verb',
 'n_low_synsets_adj',
 'n_low_synsets_adv',
 'n_entities',
 'n_org',
 'n_cardinal',
 'n_date',
 'n_gpe',
 'n_person',
 'n_money',
 'n_product',
 'n_time',
 'n_percent',
 'n_work_of_art',
 'n_quantity',
 'n_norp',
 'n_loc',
 'n_event',
 'n_ordinal',
 'n_fac',
 'n_law',
 'n_language',
 'question',
 'stance',
 'sociodemographic_info',
 'sociodemographic_group',
 'info',
 'pro',
 'contra',
 'context',
 'model',
 'language',
 'gender',
 'age',
 'education',
 'civil_status',
 'denomination',
 'residence',
 'political_spectrum',
 'ID_question',
 'topic']

In [34]:
feats = df.columns[3:166]

In [35]:
feats

['raw_sequence_length',
 'n_tokens',
 'n_sentences',
 'tokens_per_sentence',
 'n_characters',
 'avg_word_length',
 'n_types',
 'n_long_words',
 'n_lemmas',
 'n_VERB_VerbForm_Fin',
 'n_VERB_VerbForm_Inf',
 'n_VERB_VerbForm_Part',
 'n_VERB_Mood_Imp',
 'n_VERB_Mood_Ind',
 'n_VERB_Mood_Sub',
 'n_VERB_Tense_Past',
 'n_VERB_Tense_Pres',
 'n_VERB_Person_1',
 'n_VERB_Person_2',
 'n_VERB_Person_3',
 'n_VERB_Number_Plur',
 'n_VERB_Number_Sing',
 'n_NOUN_Gender_Fem',
 'n_NOUN_Gender_Masc',
 'n_NOUN_Number_Plur',
 'n_NOUN_Number_Sing',
 'n_PRON_PronType_Dem',
 'n_PRON_PronType_Int',
 'n_PRON_PronType_Prs',
 'n_PRON_PronType_Rel',
 'n_PRON_Gender_Fem',
 'n_PRON_Gender_Masc',
 'n_PRON_Number_Plur',
 'n_PRON_Number_Sing',
 'n_PRON_Person_1',
 'n_PRON_Person_3',
 'n_ADJ_Gender_Fem',
 'n_ADJ_Gender_Masc',
 'n_ADJ_Number_Plur',
 'n_ADJ_Number_Sing',
 'n_DET_Gender_Fem',
 'n_DET_Gender_Masc',
 'n_DET_Number_Plur',
 'n_DET_Number_Sing',
 'n_DET_Definite_Def',
 'n_DET_Definite_Ind',
 'tree_width',
 'tree_depth',
 'tree_branching',
 'n_noun_chunks',
 'n_dependency_cc',
 'n_dependency_dep',
 'n_dependency_punct',
 'n_positive_sentiment',
 'n_negative_sentiment',
 'sentiment_score',
 'avg_valence',
 'n_low_valence',
 'n_high_valence',
 'avg_arousal',
 'n_low_arousal',
 'n_high_arousal',
 'avg_dominance',
 'n_low_dominance',
 'n_high_dominance',
 'avg_intensity_anger',
 'avg_intensity_anticipation',
 'avg_intensity_disgust',
 'avg_intensity_fear',
 'avg_intensity_joy',
 'avg_intensity_sadness',
 'avg_intensity_surprise',
 'avg_intensity_trust',
 'n_low_intensity_anger',
 'n_low_intensity_anticipation',
 'n_low_intensity_disgust',
 'n_low_intensity_fear',
 'n_low_intensity_joy',
 'n_low_intensity_sadness',
 'n_low_intensity_surprise',
 'n_low_intensity_trust',
 'n_high_intensity_anger',
 'n_high_intensity_anticipation',
 'n_high_intensity_disgust',
 'n_high_intensity_fear',
 'n_high_intensity_joy',
 'n_high_intensity_sadness',
 'n_high_intensity_surprise',
 'n_high_intensity_trust',
 'compressibility',
 'entropy',
 'lemma_token_ratio',
 'ttr',
 'rttr',
 'cttr',
 'herdan_c',
 'summer_index',
 'dugast_u',
 'maas_index',
 'n_lexical_tokens',
 'lexical_density',
 'n_hapax_legomena',
 'n_global_token_hapax_legomena',
 'n_global_lemma_hapax_legomena',
 'n_hapax_dislegomena',
 'n_global_token_hapax_dislegomena',
 'n_global_lemma_hapax_dislegomena',
 'sichel_s',
 'global_sichel_s',
 'giroud_index',
 'mtld',
 'hdd',
 'mattr',
 'msttr',
 'yule_k',
 'simpsons_d',
 'herdan_v',
 'pos_variability',
 'n_adj',
 'n_adp',
 'n_adv',
 'n_aux',
 'n_cconj',
 'n_det',
 'n_noun',
 'n_num',
 'n_pron',
 'n_propn',
 'n_punct',
 'n_sconj',
 'n_verb',
 'n_x',
 'avg_concreteness',
 'n_high_concreteness',
 'avg_sd_concreteness',
 'n_syllables',
 'n_monosyllables',
 'n_polysyllables',
 'flesch_reading_ease',
 'flesch_kincaid_grade',
 'gunning_fog',
 'ari',
 'smog',
 'cli',
 'lix',
 'rix',
 'avg_n_synsets',
 'avg_n_synsets_noun',
 'avg_n_synsets_verb',
 'avg_n_synsets_adj',
 'n_low_synsets',
 'n_high_synsets',
 'n_high_synsets_noun',
 'n_high_synsets_verb',
 'n_high_synsets_adj',
 'n_low_synsets_noun',
 'n_low_synsets_verb',
 'n_low_synsets_adj',
 'n_low_synsets_adv',
 'n_entities',
 'n_org',
 'n_cardinal',
 'n_date']

In [36]:
len(feats)

163

In [37]:
feats

['raw_sequence_length',
 'n_tokens',
 'n_sentences',
 'tokens_per_sentence',
 'n_characters',
 'avg_word_length',
 'n_types',
 'n_long_words',
 'n_lemmas',
 'n_VERB_VerbForm_Fin',
 'n_VERB_VerbForm_Inf',
 'n_VERB_VerbForm_Part',
 'n_VERB_Mood_Imp',
 'n_VERB_Mood_Ind',
 'n_VERB_Mood_Sub',
 'n_VERB_Tense_Past',
 'n_VERB_Tense_Pres',
 'n_VERB_Person_1',
 'n_VERB_Person_2',
 'n_VERB_Person_3',
 'n_VERB_Number_Plur',
 'n_VERB_Number_Sing',
 'n_NOUN_Gender_Fem',
 'n_NOUN_Gender_Masc',
 'n_NOUN_Number_Plur',
 'n_NOUN_Number_Sing',
 'n_PRON_PronType_Dem',
 'n_PRON_PronType_Int',
 'n_PRON_PronType_Prs',
 'n_PRON_PronType_Rel',
 'n_PRON_Gender_Fem',
 'n_PRON_Gender_Masc',
 'n_PRON_Number_Plur',
 'n_PRON_Number_Sing',
 'n_PRON_Person_1',
 'n_PRON_Person_3',
 'n_ADJ_Gender_Fem',
 'n_ADJ_Gender_Masc',
 'n_ADJ_Number_Plur',
 'n_ADJ_Number_Sing',
 'n_DET_Gender_Fem',
 'n_DET_Gender_Masc',
 'n_DET_Number_Plur',
 'n_DET_Number_Sing',
 'n_DET_Definite_Def',
 'n_DET_Definite_Ind',
 'tree_width',
 'tree_depth',
 'tree_branching',
 'n_noun_chunks',
 'n_dependency_cc',
 'n_dependency_dep',
 'n_dependency_punct',
 'n_positive_sentiment',
 'n_negative_sentiment',
 'sentiment_score',
 'avg_valence',
 'n_low_valence',
 'n_high_valence',
 'avg_arousal',
 'n_low_arousal',
 'n_high_arousal',
 'avg_dominance',
 'n_low_dominance',
 'n_high_dominance',
 'avg_intensity_anger',
 'avg_intensity_anticipation',
 'avg_intensity_disgust',
 'avg_intensity_fear',
 'avg_intensity_joy',
 'avg_intensity_sadness',
 'avg_intensity_surprise',
 'avg_intensity_trust',
 'n_low_intensity_anger',
 'n_low_intensity_anticipation',
 'n_low_intensity_disgust',
 'n_low_intensity_fear',
 'n_low_intensity_joy',
 'n_low_intensity_sadness',
 'n_low_intensity_surprise',
 'n_low_intensity_trust',
 'n_high_intensity_anger',
 'n_high_intensity_anticipation',
 'n_high_intensity_disgust',
 'n_high_intensity_fear',
 'n_high_intensity_joy',
 'n_high_intensity_sadness',
 'n_high_intensity_surprise',
 'n_high_intensity_trust',
 'compressibility',
 'entropy',
 'lemma_token_ratio',
 'ttr',
 'rttr',
 'cttr',
 'herdan_c',
 'summer_index',
 'dugast_u',
 'maas_index',
 'n_lexical_tokens',
 'lexical_density',
 'n_hapax_legomena',
 'n_global_token_hapax_legomena',
 'n_global_lemma_hapax_legomena',
 'n_hapax_dislegomena',
 'n_global_token_hapax_dislegomena',
 'n_global_lemma_hapax_dislegomena',
 'sichel_s',
 'global_sichel_s',
 'giroud_index',
 'mtld',
 'hdd',
 'mattr',
 'msttr',
 'yule_k',
 'simpsons_d',
 'herdan_v',
 'pos_variability',
 'n_adj',
 'n_adp',
 'n_adv',
 'n_aux',
 'n_cconj',
 'n_det',
 'n_noun',
 'n_num',
 'n_pron',
 'n_propn',
 'n_punct',
 'n_sconj',
 'n_verb',
 'n_x',
 'avg_concreteness',
 'n_high_concreteness',
 'avg_sd_concreteness',
 'n_syllables',
 'n_monosyllables',
 'n_polysyllables',
 'flesch_reading_ease',
 'flesch_kincaid_grade',
 'gunning_fog',
 'ari',
 'smog',
 'cli',
 'lix',
 'rix',
 'avg_n_synsets',
 'avg_n_synsets_noun',
 'avg_n_synsets_verb',
 'avg_n_synsets_adj',
 'n_low_synsets',
 'n_high_synsets',
 'n_high_synsets_noun',
 'n_high_synsets_verb',
 'n_high_synsets_adj',
 'n_low_synsets_noun',
 'n_low_synsets_verb',
 'n_low_synsets_adj',
 'n_low_synsets_adv',
 'n_entities',
 'n_org',
 'n_cardinal',
 'n_date']

In [38]:
# remove redundant features (features that have the same value for all arguments)
redundant_feats = []
for feature in feats:
    if df.select(pl.col(feature).n_unique()).item() == 1:
        redundant_feats.append(feature)

df = df.drop(redundant_feats)
feats = [f for f in feats if f not in redundant_feats]

In [39]:
# removing empty arguments from the dataframe
df = df.filter(pl.col("raw_sequence_length") > 0)

In [40]:
get_inf_feats(df, feats)

{'dugast_u': 8579}

In [41]:
# fill dugast_u infs with a high value (e.g., 1000) to avoid issues with the analysis
df = df.with_columns(pl.when(pl.col("dugast_u") == float("inf"))
                     .then(1000)
                     .otherwise(pl.col("dugast_u"))
                     .alias("dugast_u"))

In [42]:
get_nan_feats(df, feats)

{'hdd': 33579}

In [43]:
df.drop("hdd")
feats.remove("hdd")

In [44]:
get_null_feats(df, feats)

{'avg_valence': 71,
 'avg_arousal': 71,
 'avg_dominance': 71,
 'avg_intensity_anger': 12276,
 'avg_intensity_anticipation': 7390,
 'avg_intensity_disgust': 15592,
 'avg_intensity_fear': 9256,
 'avg_intensity_joy': 6958,
 'avg_intensity_sadness': 11833,
 'avg_intensity_surprise': 15116,
 'avg_intensity_trust': 4042,
 'avg_concreteness': 7822,
 'avg_sd_concreteness': 7822}

In [45]:
# fill null values with the mean of the respective feature
for feat in get_null_feats(df, feats).keys():
    mean_value = df.select(pl.col(feat).mean()).item()
    df = df.with_columns(pl.when(pl.col(feat).is_null())
                         .then(mean_value)
                         .otherwise(pl.col(feat))
                         .alias(feat))

In [46]:
del df_corpus, df_generated, prompts_de, prompts_fr, prompts_it, question2prompts_de, question2prompts_fr, question2prompts_it

In [47]:
len(feats)

160

# Normalization of the data

In [47]:
# token normalize the features that start with "n_" but are not in the list of features to exclude from token normalization
replace_feats = [f for f in feats if f not in
                        ["n_tokens",
                         "n_types",
                         "n_sentences",
                         "n_characters",
                         "n_lemmas",
                         "n_syllables"] and
                        f.startswith("n_")]
for feature in replace_feats:
    df = df.with_columns(
        (pl.col(feature) / pl.col("n_tokens")). \
            alias(feature)
    )

In [48]:
# standardize all features (mean=0, std=1)
for feature in feats:
    df = normalize_column(df, feature)

In [49]:
df.describe()

shape: (9, 199)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic ┆ argument ┆ argument_ ┆ prompt_id ┆ … ┆ residence ┆ political ┆ ID_questi ┆ topic     │
│ ---       ┆ ---      ┆ id        ┆ ---       ┆   ┆ ---       ┆ _spectrum ┆ on        ┆ ---       │
│ str       ┆ str      ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str       │
│           ┆          ┆ str       ┆           ┆   ┆           ┆ str       ┆ f64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count     ┆ 388220   ┆ 388220    ┆ 375462    ┆ … ┆ 30728     ┆ 84152     ┆ 388220.0  ┆ 388220    │
│ null_coun ┆ 0        ┆ 0         ┆ 12758     ┆ … ┆ 357492    ┆ 304068    ┆ 0.0       ┆ 0         │
│ t         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ mean      ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 32249.504 ┆ null      │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ 108       ┆           │
│ std       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 20.175383 ┆ null      │
│ min       ┆ 			      ┆ 202300    ┆ de_0      ┆ … ┆ Land      ┆ Links und ┆ 32216.0   ┆ Democracy │
│           ┆ 	        ┆           ┆           ┆   ┆           ┆ Konservat ┆           ┆ , Media & │
│           ┆          ┆           ┆           ┆   ┆           ┆ iv        ┆           ┆ Digitizat │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆ io…       │
│ 25%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 32229.0   ┆ null      │
│ 50%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 32249.0   ┆ null      │
│ 75%       ┆ null     ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 32264.0   ┆ null      │
│ max       ┆ �        ┆ chatcmpl- ┆ it_999    ┆ … ┆ Stadt     ┆ Rechts    ┆ 32288.0   ┆ Welfare   │
│           ┆          ┆ CR9IPAjqa ┆           ┆   ┆           ┆ und       ┆           ┆ state &   │
│           ┆          ┆ zUdb4r1tv ┆           ┆   ┆           ┆ Liberal   ┆           ┆ family    │
│           ┆          ┆ sz8…      ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Add prompting conditions

In [50]:
df = add_conditions(df)

In [51]:
df.head()

shape: (5, 199)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ argument  ┆ argument_ ┆ prompt_id ┆ raw_seque ┆ … ┆ political ┆ ID_questi ┆ topic     ┆ conditio │
│ ---       ┆ id        ┆ ---       ┆ nce_lengt ┆   ┆ _spectrum ┆ on        ┆ ---       ┆ n        │
│ str       ┆ ---       ┆ str       ┆ h         ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆           ┆ ---       ┆   ┆ str       ┆ i64       ┆           ┆ str      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Die Begre ┆ 2025-07-1 ┆ de_0      ┆ -0.783945 ┆ … ┆ null      ┆ 32216     ┆ Welfare   ┆ SD       │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆ state &   ┆          │
│ Rente auf ┆ 0.4959171 ┆           ┆           ┆   ┆           ┆           ┆ family    ┆          │
│ 1…        ┆ 36Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Die Begre ┆ 2025-07-1 ┆ de_0      ┆ -0.699438 ┆ … ┆ null      ┆ 32216     ┆ Welfare   ┆ SD       │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆ state &   ┆          │
│ Rente für ┆ 1.8350587 ┆           ┆           ┆   ┆           ┆           ┆ family    ┆          │
│ E…        ┆ 34Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Die Begre ┆ 2025-07-1 ┆ de_0      ┆ -0.495087 ┆ … ┆ null      ┆ 32216     ┆ Welfare   ┆ SD       │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆ state &   ┆          │
│ Rente auf ┆ 3.5557549 ┆           ┆           ┆   ┆           ┆           ┆ family    ┆          │
│ 1…        ┆ 15Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Die Begre ┆ 2025-07-1 ┆ de_1      ┆ -0.750142 ┆ … ┆ null      ┆ 32216     ┆ Welfare   ┆ SD       │
│ nzung der ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆ state &   ┆          │
│ Rentenhöh ┆ 4.9513965 ┆           ┆           ┆   ┆           ┆           ┆ family    ┆          │
│ e …       ┆ 43Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Ich       ┆ 2025-07-1 ┆ de_1      ┆ -0.756288 ┆ … ┆ null      ┆ 32216     ┆ Welfare   ┆ SD       │
│ denke,    ┆ 7T17:23:0 ┆           ┆           ┆   ┆           ┆           ┆ state &   ┆          │
│ die Begre ┆ 6.1802421 ┆           ┆           ┆   ┆           ┆           ┆ family    ┆          │
│ nzung der ┆ 53Z       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Save the processed full dataset

In [54]:
df["prompt_id"].value_counts().describe()

shape: (9, 3)
┌────────────┬───────────┬───────────┐
│ statistic  ┆ prompt_id ┆ count     │
│ ---        ┆ ---       ┆ ---       │
│ str        ┆ str       ┆ f64       │
╞════════════╪═══════════╪═══════════╡
│ count      ┆ 32164     ┆ 32165.0   │
│ null_count ┆ 1         ┆ 0.0       │
│ mean       ┆ null      ┆ 12.069641 │
│ std        ┆ null      ┆ 71.074897 │
│ min        ┆ de_0      ┆ 6.0       │
│ 25%        ┆ null      ┆ 12.0      │
│ 50%        ┆ null      ┆ 12.0      │
│ 75%        ┆ null      ┆ 12.0      │
│ max        ┆ it_999    ┆ 12758.0   │
└────────────┴───────────┴───────────┘

In [57]:
df.filter(pl.col("prompt_id") == "it_5399", pl.col("model") == "occiglot-7b-eu5-instruct")

shape: (6, 199)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ argument  ┆ argument_ ┆ prompt_id ┆ raw_seque ┆ … ┆ political ┆ ID_questi ┆ topic     ┆ conditio │
│ ---       ┆ id        ┆ ---       ┆ nce_lengt ┆   ┆ _spectrum ┆ on        ┆ ---       ┆ n        │
│ str       ┆ ---       ┆ str       ┆ h         ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆           ┆ ---       ┆   ┆ str       ┆ i64       ┆           ┆ str      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Sono favo ┆ 2025-09-1 ┆ it_5399   ┆ -0.264615 ┆ … ┆ null      ┆ 32253     ┆ Nature    ┆ C + SD + │
│ revole al ┆ 2T08:09:1 ┆           ┆           ┆   ┆           ┆           ┆ conservat ┆ Ex + P&C │
│ tema      ┆ 8.9907956 ┆           ┆           ┆   ┆           ┆           ┆ ion       ┆          │
│ politi…   ┆ 12        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Sono a    ┆ 2025-09-1 ┆ it_5399   ┆ -0.250786 ┆ … ┆ null      ┆ 32253     ┆ Nature    ┆ C + SD + │
│ favore    ┆ 2T08:10:0 ┆           ┆           ┆   ┆           ┆           ┆ conservat ┆ Ex + P&C │
│ del tema  ┆ 2.5229468 ┆           ┆           ┆   ┆           ┆           ┆ ion       ┆          │
│ politic…  ┆ 35        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Sono favo ┆ 2025-09-1 ┆ it_5399   ┆ -0.639516 ┆ … ┆ null      ┆ 32253     ┆ Nature    ┆ C + SD + │
│ revole a  ┆ 2T08:10:4 ┆           ┆           ┆   ┆           ┆           ┆ conservat ┆ Ex + P&C │
│ questo    ┆ 7.3393239 ┆           ┆           ┆   ┆           ┆           ┆ ion       ┆          │
│ tema …    ┆ 97        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ C         ┆ 2025-09-1 ┆ it_5399   ┆ -1.244888 ┆ … ┆ null      ┆ 32253     ┆ Nature    ┆ C + SD + │
│           ┆ 2T10:06:2 ┆           ┆           ┆   ┆           ┆           ┆ conservat ┆ Ex + P&C │
│           ┆ 1.2903394 ┆           ┆           ┆   ┆           ┆           ┆ ion       ┆          │
│           ┆ 70        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ S         ┆ 2025-09-1 ┆ it_5399   ┆ -1.09585  ┆ … ┆ null      ┆ 32253     ┆ Nature    ┆ C + SD + │
│ E         ┆ 2T10:06:5 ┆           ┆           ┆   ┆           ┆           ┆ conservat ┆ Ex + P&C │
│ E         ┆ 5.6283659 ┆           ┆           ┆   ┆           ┆           ┆ ion       ┆          │
│ S         ┆ 93        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ O U       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ L         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ A         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ J         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ S         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ P         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ S         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ¿Ma…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Un        ┆ 2025-09-1 ┆ it_5399   ┆ -1.241815 ┆ … ┆ null      ┆ 32253     ┆ Nature    ┆ C + SD + │
│           ┆ 2T10:07:4 ┆           ┆           ┆   ┆           ┆           ┆ conservat ┆ Ex + P&C │
│           ┆ 0.5541532 ┆           ┆           ┆   ┆           ┆           ┆ ion       ┆          │
│           ┆ 04        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [58]:
df.filter(pl.col("prompt_id") == "it_5398", pl.col("model") == "occiglot-7b-eu5-instruct")

shape: (3, 199)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ argument  ┆ argument_ ┆ prompt_id ┆ raw_seque ┆ … ┆ political ┆ ID_questi ┆ topic     ┆ conditio │
│ ---       ┆ id        ┆ ---       ┆ nce_lengt ┆   ┆ _spectrum ┆ on        ┆ ---       ┆ n        │
│ str       ┆ ---       ┆ str       ┆ h         ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆           ┆ ---       ┆   ┆ str       ┆ i64       ┆           ┆ str      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ È imperat ┆ 2025-09-1 ┆ it_5398   ┆ -0.696365 ┆ … ┆ null      ┆ 32253     ┆ Nature    ┆ C + SD + │
│ ivo che   ┆ 2T08:09:1 ┆           ┆           ┆   ┆           ┆           ┆ conservat ┆ Ex + P&C │
│ le        ┆ 8.9907779 ┆           ┆           ┆   ┆           ┆           ┆ ion       ┆          │
│ aziende   ┆ 69        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ag…       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ "Come     ┆ 2025-09-1 ┆ it_5398   ┆ -0.578056 ┆ … ┆ null      ┆ 32253     ┆ Nature    ┆ C + SD + │
│ giovane   ┆ 2T08:10:0 ┆           ┆           ┆   ┆           ┆           ┆ conservat ┆ Ex + P&C │
│ cittadino ┆ 2.5229306 ┆           ┆           ┆   ┆           ┆           ┆ ion       ┆          │
│ svizze…   ┆ 21        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Sostengo  ┆ 2025-09-1 ┆ it_5398   ┆ -0.616468 ┆ … ┆ null      ┆ 32253     ┆ Nature    ┆ C + SD + │
│ l'idea di ┆ 2T08:10:4 ┆           ┆           ┆   ┆           ┆           ┆ conservat ┆ Ex + P&C │
│ riservare ┆ 7.3393075 ┆           ┆           ┆   ┆           ┆           ┆ ion       ┆          │
│ p…        ┆ 47        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [52]:
df.write_csv("full_corpus.csv")